robot:
  # Unique identifier for the robot setup (e.g., aloha_stationary)
  name: aloha_stationary_arms

  # Leader Arm Configuration (Human-controlled)
  leader_arms:
    - # Identifier for the stationary leader arm (naming convention: leader_<unique_identification>)
      name: leader_right

      # Model type for calibration and compatibility
      model: aloha_wx250s

      # Orientation or side of the arm (options: left, right)
      orientation: right

      # Position and orientation of arm in space (applied for visualization tools like RVIZ)
      transform: [-0.5, -0.25, 0.0, 0.0, 0.0, 0.0, 1.0]

    - # Identifier for the left leader arm
      name: leader_left

      # Model type for calibration and compatibility
      model: aloha_wx250s

      # Orientation or side of the arm
      orientation: left

      # Position and orientation of arm in space
      transform: [-0.5, 0.25, 0.0, 0.0, 0.0, 0.0, 1.0]

  # Follower Arm Configuration (Robot-controlled)
  follower_arms:
    - # Unique name for the stationary follower arm (naming convention: follower_<unique_identification>)
      name: follower_right

      # Model type for calibration and compatibility
      model: aloha_vx300s

      # Orientation or side of the arm
      orientation: right

      # Position and orientation of arm in space
      transform: [0.5, -0.25, 0.0, 0.0, 0.0, 0.0, 1.0]

    - # Identifier for the left follower arm
      name: follower_left

      # Model type for calibration and compatibility
      model: aloha_vx300s

      # Orientation or side of the arm
      orientation: left

      # Position and orientation of arm in space
      transform: [0.5, 0.25, 0.0, 0.0, 0.0, 0.0, 1.0]

  # Base configuration
  base: false
