mobile_base:
  base_joystick_teleop:
    ros__parameters:
      axis_linear:
        x: 1
      scale_linear:
        x: 0.7

      axis_angular:
        yaw: 3
      scale_angular:
        yaw: 0.6

      enable_button: 6  # L2 shoulder button
